CREATE TABLE [dbo].[StudentInfo] (
    [Id]                        INT     IDENTITY(1,1)    NOT NULL,
    [Birthdate]                 DATE          NOT NULL,
    [BirthPlace]                NVARCHAR (50) NOT NULL,
    [DegreeId]                  TINYINT       NOT NULL,
    [Citizenship]               NVARCHAR (30) NOT NULL,
    [GraduatedSchoolName]       NVARCHAR (170)NULL,
    [GraduatedYear]             INT           NULL,
    [MaritalStatusId]           TINYINT       DEFAULT ((1)) NOT NULL,
    [Registration]              NVARCHAR (170) NOT NULL,
    [Exemption]                 NVARCHAR (100) NOT NULL,
    [ExperienceCompetitionId]   TINYINT       DEFAULT ((1)) NOT NULL,
    [TransferFrom]              NVARCHAR (170)NULL,
    [TransferDirection]         NVARCHAR (170)NULL,
    [CompetitionConditions]     NVARCHAR (100) NULL,
    [OutOfCompetitionInfo]      NVARCHAR (100) NULL,
    [AmendsId]                  TINYINT       DEFAULT ((1)) NOT NULL,
    [EmploymentNumber]          INT           NULL,
    [EmploymentAuthority]       NVARCHAR (30) NULL,
    [EmploymentGivenDate]       DATE          NULL,
    [OrderNumber]               NVARCHAR(10)           NULL,
    [OrderDate]                 DATE          NULL,
    [RegistrOrPassportNumber]   NVARCHAR (25) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([AmendsId]) REFERENCES [dbo].[Amends] ([Id]),
    FOREIGN KEY ([ExperienceCompetitionId]) REFERENCES [dbo].[ExperienceCompetitions] ([Id]),
    FOREIGN KEY ([MaritalStatusId]) REFERENCES [dbo].[MaritalStatus] ([Id]),
    FOREIGN KEY ([DegreeId]) REFERENCES [dbo].[Degree] (Id),
    UNIQUE ([RegistrOrPassportNumber])
);

